# AUTO-GENERATED by planner node. This file is overwritten each iteration.
# Do not edit manually — changes will be lost.
import pandas as pd
import numpy as np

def nr4_weekly_range_expansion(df: pd.DataFrame) -> tuple[dict, pd.DataFrame]:
    params = {
        "signal": "Detects when the current weekly bar has the narrowest range of the last 4 weeks (NR4), then the following week breaks to a range at least 1.5x the 10-week average range. Returns are measured starting after the range expansion week.",
        "field": "high, low, close",
        "nr4_lookback": 4,
        "range_expansion_multiplier": 1.5,
        "range_average_lookback": 10,
        "forward_weeks": [1, 2, 4]
    }

    rng = df["high"] - df["low"]
    # Find NR4 weeks: range is minimum of 4-week window ending at this week
    nr4 = rng == rng.rolling(params["nr4_lookback"]).min()
    # Only consider NR4 weeks that are not at the very beginning
    nr4_shift = nr4.shift(0)

    # Next week range expansion:
    avg_rng = rng.rolling(params["range_average_lookback"]).mean()
    next_rng = rng.shift(-1)
    next_avg_rng = avg_rng.shift(-1)
    expansion = next_rng >= params["range_expansion_multiplier"] * next_avg_rng

    # Signal mask: NR4 week followed by range expansion week
    signal_mask = nr4_shift & expansion
    signal_idx = signal_mask[signal_mask].index
    # Returns start from week AFTER the range expansion week
    result_idx = signal_idx + 1  # But index is not necessarily integer, get proper rows
    signal_rows = df.index.isin(result_idx)

    # For those indices, get date and close
    result = df.loc[signal_rows, ["date", "close"]].copy()
    start_idx = result.index

    # Compute forward returns
    for fw in params["forward_weeks"]:
        result[f"fwd_{fw}d"] = (df["close"].shift(-fw).loc[start_idx] / df["close"].loc[start_idx]) * 100 - 100

    return params, result

