# AUTO-GENERATED by planner node. This file is overwritten each iteration.
# Do not edit manually — changes will be lost.
import pandas as pd
import numpy as np

def vwap_crossover_with_intraday_volume_spike(df: pd.DataFrame) -> tuple[dict, pd.DataFrame]:
    params = {
        "signal": "Signal when the close price crosses above intraday VWAP AND volume is at least 1.5x the rolling 20-bar average volume. Only triggers on upward cross.",
        "field": ["close", "volume"],
        "vwap_window": "All bars since session start (per day)",
        "volume_spike_multiple": 1.5,
        "volume_rolling_window": 20,
        "forward_bars": [1, 5]
    }

    df = df.copy()
    df["date"] = pd.to_datetime(df["date"])
    df["date_only"] = df["date"].dt.normalize()

    # Calculate intraday cumulative sum per session for VWAP
    df["cum_vol_x_price"] = df["close"] * df["volume"]
    df["cum_vol_x_price_cumsum"] = df.groupby("date_only")["cum_vol_x_price"].cumsum()
    df["cum_volume_cumsum"] = df.groupby("date_only")["volume"].cumsum()
    df["vwap"] = df["cum_vol_x_price_cumsum"] / df["cum_volume_cumsum"]
    
    # Volume spike: volume >= 1.5x 20-bar rolling mean (non-overlapping day boundaries)
    df["rolling_vol"] = df.groupby("date_only")["volume"].transform(lambda x: x.rolling(20, min_periods=1).mean())
    vol_spike = df["volume"] >= (1.5 * df["rolling_vol"])
    
    # VWAP upward cross
def _upward_cross(series, ref):
        prev = series.shift(1)
        prev_ref = ref.shift(1)
        return (prev < prev_ref) & (series > ref)
    cross = _upward_cross(df["close"], df["vwap"])
    
    mask = cross & vol_spike
    result = df.loc[mask, ["date", "close"]].copy()
    for k in [1,5]:
        result[f"fwd_{k}d"] = df["close"].shift(-k).loc[mask].values / df["close"].loc[mask].values * 100 - 100
    return params, result
