# AUTO-GENERATED by planner node. This file is overwritten each iteration.
# Do not edit manually — changes will be lost.
import pandas as pd
import numpy as np

def broken_syntax(df):
    return (],  # syntax error

def broken_runtime(df):
    return df.loc[[999999999]], df

def good_one(df):
    params = {'signal': 'working'}
    out = df.head(3).copy()
    out['fwd_1d'] = [1.0, -0.5, 2.0]
    return params, out

