# AUTO-GENERATED by planner node. This file is overwritten each iteration.
# Do not edit manually — changes will be lost.
import pandas as pd
import numpy as np

def weekly_failed_breakout_long(df: pd.DataFrame) -> tuple[dict, pd.DataFrame]:
    params = {
        "signal": "Weekly failed breakout: This week's high breaks prior 20-week high, but weekly close falls back below prior week's high. Long entry on the week following signal.",
        "field": "high, close",
        "lookback_high": 20,
        "close_below_prior_high": True,
        "forward_weeks": [1, 2, 4]
    }

    # Compute prior 20-week rolling high (excluding current week)
    prior_20w_high = df["high"].shift(1).rolling(window=20, min_periods=20).max()
    # Prior week's high (for close comparison)
    prior_high = df["high"].shift(1)

    # Conditions:
    # 1. This week's high breaks prior 20-week high
    breakout = df["high"] > prior_20w_high
    # 2. This week's close falls back below prior week's high
    close_below_prior = df["close"] < prior_high

    # Signal: both conditions met
    signal_mask = breakout & close_below_prior
    # Shift signal to anticipate entry on next week's open (since candle completes at close)
    mask = signal_mask.shift(1).fillna(False)

    result = df.loc[mask, ["date", "close"]].copy()
    result["fwd_1d"] = df["close"].shift(-1).loc[mask].values / result["close"] * 100 - 100
    result["fwd_2d"] = df["close"].shift(-2).loc[mask].values / result["close"] * 100 - 100
    result["fwd_4d"] = df["close"].shift(-4).loc[mask].values / result["close"] * 100 - 100

    return params, result
