# AUTO-GENERATED by planner node. This file is overwritten each iteration.
# Do not edit manually — changes will be lost.
import pandas as pd
import numpy as np

def bearish_engulfing_signal(df: pd.DataFrame) -> tuple[dict, pd.DataFrame]:
    params = {
        "signal": "Bearish engulfing pattern: Day N opens higher and closes lower than previous day, and entire body (open to close) of day N fully engulfs prior day's body (including open and close). Measures forward returns after pattern appears.",
        "field": "open, close",
        "engulfing_criteria": "today's open > yesterday's close and today's close < yesterday's open, and today's real body fully engulfs previous day's real body",
        "forward_days": [1, 5],
    }
    o = df['open']
    c = df['close']
    o_prev = o.shift(1)
    c_prev = c.shift(1)
    
    # Today's body direction: opens above prior close, closes below prior open
    direction_cond = (o > c_prev) & (c < o_prev)
    
    # Today's body fully engulfs prior body's range (open and close)
    today_body_max = np.maximum(o, c)
    today_body_min = np.minimum(o, c)
    prev_body_max = np.maximum(o_prev, c_prev)
    prev_body_min = np.minimum(o_prev, c_prev)
    engulf_cond = (today_body_max >= prev_body_max) & (today_body_min <= prev_body_min)
    
    mask = direction_cond & engulf_cond
    result = df.loc[mask, ["date", "close"]].copy()
    result["fwd_1d"] = df["close"].shift(-1).loc[mask].values / df["close"].loc[mask].values * 100 - 100
    result["fwd_5d"] = df["close"].shift(-5).loc[mask].values / df["close"].loc[mask].values * 100 - 100
    return params, result

