# AUTO-GENERATED by planner node. This file is overwritten each iteration.
# Do not edit manually — changes will be lost.
import pandas as pd
import numpy as np

def nr7_then_range_expansion(df: pd.DataFrame) -> tuple[dict, pd.DataFrame]:
    params = {
        "signal": "Signal is True on bars where the previous bar is an NR7 (its high-low range is the narrowest of the past 7 bars), AND the current bar's range is at least 2x the prior bar's range (range expansion). Measures forward returns from bars after expansion.",
        "field": "high, low",
        "nrN_lookback": 7,
        "expansion_mult": 2.0,
        "forward_bars": [1, 5]
    }
    
    rng = df['high'] - df['low']
    nr7 = rng.rolling(7, min_periods=7).apply(lambda x: x[-1] == np.min(x), raw=True).astype(bool)
    nr7_prev = nr7.shift(1)
    # For bars where previous is NR7 and current range expansion
    rng_prev = rng.shift(1)
    expansion = rng >= (2.0 * rng_prev)
    mask = nr7_prev & expansion
    result = df.loc[mask, ['date', 'close']].copy()
    # Forward returns
    for bars in params["forward_bars"]:
        result[f"fwd_{bars}d"] = df['close'].shift(-bars).loc[mask].values / result['close'] * 100 - 100
    return params, result

