# AUTO-GENERATED by refinement planner. This file is overwritten each iteration.
# Do not edit manually — changes will be lost.
import pandas as pd
import numpy as np

def nr7_breakout_with_weekly_silent_top_avoidance_and_compression_quality(df_5min, df_daily, df_weekly):
    import numpy as np
    import pandas as pd

    params = {
        'signal': 'NR7 + range expansion breakout long with compression-quality filter, weekly uptrend, and silent-top avoidance',
        'entry_timeframe': 'daily',
        'exit_timeframe': 'daily',
        'entry_condition': 'NR7 + tight compression (range in bottom 25% of 20d) + 2x expansion + close top 20% + weekly>10w SMA + no silent top',
        'exit_condition': 'forward 1,2,5,10 days',
        'derived_from': ['nr7_breakout_with_weekly_silent_top_avoidance', 'nr7_then_range_expansion_breakout', 'weekly_silent_top_exhaustion'],
        'refinement_type': 'tightening',
        'nr7_lookback': 7,
        'compression_percentile_lookback': 20,
        'compression_percentile_threshold': 0.25,
        'expansion_multiplier': 2.0,
        'close_position_threshold': 0.8,
        'weekly_ma_lookback': 10,
        'forward_days': [1, 2, 5, 10],
    }

    d = df_daily.copy().reset_index(drop=True)
    d['date'] = pd.to_datetime(d['date'])
    d['range'] = d['high'] - d['low']

    # NR7: today's range is min of last 7 (inclusive)
    d['nr7'] = d['range'] == d['range'].rolling(7).min()

    # Compression quality: range in bottom 25th percentile of last 20 days
    d['range_pct20'] = d['range'].rolling(20).rank(pct=True)
    d['compressed'] = d['range_pct20'] <= 0.25

    # Expansion day metrics
    prev_range = d['range'].shift(1)
    expansion = d['range'] > 2.0 * prev_range
    rng_safe = d['range'].replace(0, np.nan)
    close_pos = (d['close'] - d['low']) / rng_safe
    bullish_close = close_pos >= 0.8

    # NR7 + compression on prior day
    prior_nr7_compressed = d['nr7'].shift(1).fillna(False) & d['compressed'].shift(1).fillna(False)

    base_signal = prior_nr7_compressed & expansion & bullish_close

    # Weekly features
    w = df_weekly.copy().reset_index(drop=True)
    w['date'] = pd.to_datetime(w['date'])
    w['range'] = w['high'] - w['low']
    w['body'] = (w['close'] - w['open']).abs()
    w['sma10'] = w['close'].rolling(10).mean()
    w['hh52'] = w['high'].rolling(52).max()
    w['new_52w_high'] = w['high'] >= w['hh52']
    w['range_pct26'] = w['range'].rolling(26).rank(pct=True)
    w_range_safe = w['range'].replace(0, np.nan)
    w['body_ratio'] = w['body'] / w_range_safe
    w['silent_top'] = w['new_52w_high'] & (w['range_pct26'] <= 0.30) & (w['body_ratio'] < 0.30)
    w['above_10w'] = w['close'] > w['sma10']

    # Use most recently COMPLETED week — shift by 1 then ffill to daily
    w_sorted = w.sort_values('date').reset_index(drop=True)
    w_sorted['silent_top_prev'] = w_sorted['silent_top'].shift(1)
    w_sorted['above_10w_prev'] = w_sorted['above_10w'].shift(1)

    weekly_idx = w_sorted.set_index('date')
    daily_dates = pd.DatetimeIndex(d['date'])
    silent_top_aligned = weekly_idx['silent_top_prev'].reindex(
        weekly_idx.index.union(daily_dates)
    ).sort_index().ffill().reindex(daily_dates)
    above_10w_aligned = weekly_idx['above_10w_prev'].reindex(
        weekly_idx.index.union(daily_dates)
    ).sort_index().ffill().reindex(daily_dates)

    d['silent_top_recent'] = silent_top_aligned.values
    d['weekly_uptrend'] = above_10w_aligned.values

    full_signal = (
        base_signal
        & (d['silent_top_recent'].fillna(False) == False)
        & (d['weekly_uptrend'].fillna(False) == True)
    )

    for n in [1, 2, 5, 10]:
        d[f'fwd_{n}d'] = d['close'].shift(-n) / d['close'] * 100 - 100

    result = d.loc[full_signal, ['date', 'close', 'fwd_1d', 'fwd_2d', 'fwd_5d', 'fwd_10d']].copy()
    result = result.dropna(subset=['fwd_1d', 'fwd_2d', 'fwd_5d', 'fwd_10d'])
    return params, result.reset_index(drop=True)

