"""Multi-timeframe backtest engine for refinement strategies."""

import importlib
import importlib.util
import sys
from pathlib import Path

import pandas as pd

from backtest import load


def load_all(index: str = "NIFTY") -> dict[str, pd.DataFrame]:
    """Load all 3 timeframes once. Returns dict keyed by timeframe."""
    return {
        "5min": load(index, "5min"),
        "daily": load(index, "daily"),
        "weekly": load(index, "weekly"),
    }


def execute_multi_strategies(
    index: str,
    strategy_defs: list,
) -> list[tuple[dict, pd.DataFrame]]:
    """Execute refinement strategies that can access all timeframes.

    Each strategy function receives 3 DataFrames:
        def strategy(df_5min, df_daily, df_weekly) -> (params, result_df)
    """
    # 1. Write strategy file
    strat_file = Path("strategies/strat_mixed.py")
    strat_file.parent.mkdir(exist_ok=True)

    file_lines = [
        "# AUTO-GENERATED by refinement planner. This file is overwritten each iteration.",
        "# Do not edit manually — changes will be lost.",
        "import pandas as pd",
        "import numpy as np",
        "",
    ]
    for sdef in strategy_defs:
        file_lines.append(sdef["code"])
        file_lines.append("")

    strat_file.write_text("\n".join(file_lines))

    # 2. Import
    module_name = "strat_mixed"
    spec = importlib.util.spec_from_file_location(module_name, strat_file)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = mod
    spec.loader.exec_module(mod)

    # 3. Load all timeframes once
    data = load_all(index)

    # 4. Execute — each strategy gets all 3 DataFrames
    results = []
    for sdef in strategy_defs:
        try:
            fn = getattr(mod, sdef["name"])
            params, result_df = fn(data["5min"], data["daily"], data["weekly"])
            results.append((params, result_df))
        except Exception as e:
            print(f"[WARN] Strategy {sdef['name']} failed: {e}")
            results.append((sdef["params"], pd.DataFrame()))

    return results
