"""Multi-timeframe backtest engine for refinement strategies."""

from pathlib import Path

import pandas as pd

from backtest import _exec_single, load, log_attempt
from config import CFG

_TIMEFRAMES = CFG["timeframes"]


def load_all(index: str = "NIFTY") -> dict[str, pd.DataFrame]:
    """Load all timeframes once. Returns dict keyed by timeframe."""
    return {tf: load(index, tf) for tf in _TIMEFRAMES}


def execute_multi_strategies(
    index: str,
    strategy_defs: list,
) -> tuple[list[tuple[dict, pd.DataFrame]], str, str]:
    """Execute refinement strategies that can access all timeframes.

    Each strategy receives one DataFrame per configured timeframe (in config order).
    Strategies run in isolated namespaces so one bad strategy doesn't kill the
    batch. Every attempt is recorded under timeframe='mixed' for planner memory.

    Returns:
        (results, data_from, data_to) — results list plus the widest data date range.
    """
    # 1. Write consolidated file (for inspection only; execution is per-strategy).
    strat_file = Path("strategies/strat_mixed.py")
    strat_file.parent.mkdir(exist_ok=True)

    file_lines = [
        "# AUTO-GENERATED by refinement planner. This file is overwritten each iteration.",
        "# Do not edit manually — changes will be lost.",
        "import pandas as pd",
        "import numpy as np",
        "",
    ]
    for sdef in strategy_defs:
        file_lines.append(sdef["code"])
        file_lines.append("")
    strat_file.write_text("\n".join(file_lines))

    # 2. Load all timeframes once; compute widest data range.
    data = load_all(index)
    all_dates = []
    for df in data.values():
        if not df.empty:
            all_dates.append(df["date"].min())
            all_dates.append(df["date"].max())
    data_from = str(min(all_dates).date()) if all_dates else None
    data_to = str(max(all_dates).date()) if all_dates else None

    # 3. Execute each strategy in isolation.
    dfs = [data[tf] for tf in _TIMEFRAMES]
    results = []
    for sdef in strategy_defs:
        params, result_df, status, error = _exec_single(sdef, dfs)
        results.append((params, result_df))
        log_attempt(
            timeframe="mixed",
            strategy=sdef["name"],
            params=sdef.get("params", {}),
            status=status,
            signals=len(result_df) if not result_df.empty else 0,
            error=error,
        )

    return results, data_from, data_to
